server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgsecret
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: pgsecret
    validate-on-migrate: true

eventstore:
  storage: pg